<a href="https://colab.research.google.com/github/AryaTV98/AryaTV/blob/main/diabetes_naive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
print(df.columns)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')


In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.tail()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [ ]:
df.shape

(768, 9)

In [ ]:
print(df.isna().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)
x_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
181            0      119             64             18       92  34.9   
499            6      154             74             32      193  29.3   
508            2       84             50             23       76  30.4   
696            3      169             74             19      125  29.9   
84             5      137            108              0        0  48.8   
..           ...      ...            ...            ...      ...   ...   
302            5       77             82             41       42  35.8   
115            4      146             92              0        0  31.2   
760            2       88             58             26       16  28.4   
608            0      152             82             39      272  41.5   
561            0      198             66             32      274  41.3   

     DiabetesPedigreeFunction  Age  
181                     0.725   23  
499                     0.839   39  
508                     0.968   21  
696                     0.268   31  
84                      0.227   37  
..                        ...  ...  
302                     0.156   35  
115                     0.539   61  
760                     0.766   22  
608                     0.270   27  
561                     0.502   28  

[537 rows x 8 columns]

In [ ]:
y_train

181    0
499    0
508    0
696    1
84     1
      ..
302    0
115    1
760    0
608    0
561    1
Name: Outcome, Length: 537, dtype: int64

In [ ]:
x_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
7             10      115              0              0        0  35.3   
714            3      102             74              0        0  29.5   
22             7      196             90              0        0  39.8   
201            1      138             82              0        0  40.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
623            0       94             70             27      115  43.5   
568            4      154             72             29      126  31.3   
381            0      105             68             22        0  20.0   
599            1      109             38             18      120  23.1   
109            0       95             85             25       36  37.4   

     DiabetesPedigreeFunction  Age  
7                       0.134   29  
714                     0.121   32  
22                      0.451   41  
201                     0.236   28  
4                       2.288   33  
..                        ...  ...  
623                     0.347   21  
568                     0.338   37  
381                     0.236   22  
599                     0.407   26  
109                     0.247   24  

[231 rows x 8 columns]

In [ ]:
y_test

7      0
714    0
22     1
201    0
4      1
      ..
623    0
568    0
381    0
599    0
109    1
Name: Outcome, Length: 231, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-1.1529178 , -0.08113554, -0.27578377, ...,  0.3436327 ,
         0.74380989, -0.85071219],
       [ 0.66801414,  0.99808774,  0.24660031, ..., -0.35996385,
         1.09064998,  0.52347829],
       [-0.54594049, -1.16035882, -1.00712149, ..., -0.22175739,
         1.48312692, -1.022486  ],
       ...,
       [-0.54594049, -1.03701902, -0.58921422, ..., -0.47304187,
         0.86855063, -0.9365991 ],
       [-1.1529178 ,  0.93641784,  0.66450757, ...,  1.1728715 ,
        -0.640508  , -0.50716457],
       [-1.1529178 ,  2.35482558, -0.17130696, ...,  1.14774305,
         0.065342  , -0.42127767]])

In [ ]:
x_test

array([[ 1.88196876, -0.20447534, -3.61904188, ...,  0.3938896 ,
        -1.05428214, -0.33539076],
       [-0.24245183, -0.60532971,  0.24660031, ..., -0.33483541,
        -1.09383408, -0.07773005],
       [ 0.97150279,  2.29315568,  1.08241483, ...,  0.95927969,
        -0.0898233 ,  0.6952521 ],
       ...,
       [-1.1529178 , -0.51282485, -0.06683014, ..., -1.52843671,
        -0.74395153, -0.9365991 ],
       [-0.84942914, -0.38948505, -1.63398238, ..., -1.13894576,
        -0.2236914 , -0.59305148],
       [-1.1529178 , -0.82117436,  0.82122279, ...,  0.65773831,
        -0.71048451, -0.76482529]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)
print(model.predict([[10,115,0,0,0,35.3,0.134,29]]))

[1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0 0 1 0 1 1 1 0 1 0 1 1 0 0 1 0 0 1 0 0
 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0
 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 1
 0 0 0 1 0 0 0 1 1 1 0 1 0 1 0 0 1 1 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 0 1
 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 0 0
 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 1
 1 1 0 0 0 0 0 0 0]
[1]


In [ ]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
labels=['yes','no']
result=confusion_matrix(y_test,y_pred)
print(result)
score=accuracy_score(y_test,y_pred)
score


[[130  25]
 [ 29  47]]


0.7662337662337663