<a href="https://colab.research.google.com/github/AryaTV98/AryaTV/blob/main/heart_naive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/heart.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [ ]:
print(df.columns)

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')


In [ ]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [ ]:
df.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0

In [ ]:
df.shape

(1025, 14)

In [ ]:
print(df.isna().sum())

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64


In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
x
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30)
x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
268   58    1   2       132   224    0        0      173      0      3.2   
104   52    1   3       118   186    0        0      190      0      0.0   
774   48    0   2       130   275    0        1      139      0      0.2   
399   63    1   3       145   233    1        0      150      0      2.3   
417   52    1   2       138   223    0        1      169      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
544   54    1   2       125   273    0        0      152      0      0.5   
743   58    1   1       125   220    0        1      144      0      0.4   
201   34    1   3       118   182    0        0      174      0      0.0   
947   54    0   2       160   201    0        1      163      0      0.0   
766   57    1   0       110   335    0        1      143      1      3.0   

     slope  ca  thal  
268      2   2     3  
104      1   0     1  
774      2   0     2  
399      0   0     1  
417      2   4     2  
..     ...  ..   ...  
544      0   1     2  
743      1   4     3  
201      2   0     2  
947      2   1     2  
766      1   1     3  

[717 rows x 13 columns]

In [ ]:
x_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
367   48    1   1       110   229    0        1      168      0      1.0   
426   54    0   2       160   201    0        1      163      0      0.0   
190   41    1   2       112   250    0        1      179      0      0.0   
188   63    1   0       130   254    0        0      147      0      1.4   
796   41    1   1       135   203    0        1      132      0      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
982   67    0   0       106   223    0        1      142      0      0.3   
802   63    0   0       124   197    0        1      136      1      0.0   
31    50    0   1       120   244    0        1      162      0      1.1   
356   59    1   0       164   176    1        0       90      0      1.0   
82    46    1   2       150   231    0        1      147      0      3.6   

     slope  ca  thal  
367      0   0     3  
426      2   1     2  
190      2   0     2  
188      1   1     3  
796      1   0     1  
..     ...  ..   ...  
982      2   2     2  
802      1   0     2  
31       2   0     2  
356      1   2     1  
82       1   0     2  

[308 rows x 13 columns]

In [ ]:
y_train

268    0
104    1
774    1
399    1
417    1
      ..
544    1
743    1
201    1
947    1
766    0
Name: target, Length: 717, dtype: int64

In [ ]:
y_test

367    0
426    1
190    1
188    0
796    1
      ..
982    1
802    0
31     1
356    0
82     0
Name: target, Length: 308, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.401491  ,  0.67187574,  1.02188251, ...,  0.9893364 ,
         1.17808919,  1.11223507],
       [-0.26078442,  0.67187574,  1.996204  , ..., -0.63762277,
        -0.71796008, -2.12294768],
       [-0.70230136, -1.48837046,  1.02188251, ...,  0.9893364 ,
        -0.71796008, -0.5053563 ],
       ...,
       [-2.24761066,  0.67187574,  1.996204  , ...,  0.9893364 ,
        -0.71796008, -0.5053563 ],
       [-0.04002594, -1.48837046,  1.02188251, ...,  0.9893364 ,
         0.23006456, -0.5053563 ],
       [ 0.29111176,  0.67187574, -0.92676047, ..., -0.63762277,
         0.23006456,  1.11223507]])

In [ ]:
x_test

array([[-0.70230136,  0.67187574,  0.04756102, ..., -2.26458194,
        -0.71796008,  1.11223507],
       [-0.04002594, -1.48837046,  1.02188251, ...,  0.9893364 ,
         0.23006456, -0.5053563 ],
       [-1.47495601,  0.67187574,  1.02188251, ...,  0.9893364 ,
        -0.71796008, -0.5053563 ],
       ...,
       [-0.48154289, -1.48837046,  0.04756102, ...,  0.9893364 ,
        -0.71796008, -0.5053563 ],
       [ 0.51187024,  0.67187574, -0.92676047, ..., -0.63762277,
         1.17808919, -2.12294768],
       [-0.92305983,  0.67187574,  1.02188251, ..., -0.63762277,
        -0.71796008, -0.5053563 ]])

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(y_pred)
print(model.predict([[52,1,0,125,212,0,1,168,0,1.0,2,2,3]]))

[1 1 1 0 1 0 0 1 0 1 0 0 1 0 1 1 0 1 0 0 1 0 0 0 0 1 1 1 0 0 0 1 0 1 0 1 1
 1 0 1 1 1 0 0 1 0 0 0 1 1 0 1 0 1 1 1 0 1 1 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0
 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 0 0 1 1 0 1 0 1 0 1 1 1 0 0 1 0 0 0 0 0 1 0
 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1 1 1 0 1 1 1 0
 0 0 0 1 1 0 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 0 0 0 1 1 1 0 1 1 0 1 0 0 0 1 0
 0 1 1 1 1 0 0 0 0 1 1 1 0 1 0 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 1 0 1 0 0 1
 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 0 1 1 0 1 1 1 1 1 0 0 1 1 1 1 0 1 0 1 1 1 0
 0 0 1 0 1 1 0 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 1 1 0 1 0 1 0 1 0
 1 1 0 1 0 1 1 1 0 1 0 0]
[0]


In [ ]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
labels=['yes','no']
result=confusion_matrix(y_test,y_pred)
print(result)
score=accuracy_score(y_test,y_pred)
score


[[130  25]
 [ 29  47]]


0.7662337662337663